---
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: start haproxy
  service:
    name: haproxy
    state: started

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
