---
- name: install httpd and httpie
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - httpie

- name: enable apache at boot
  service:
    name: httpd
    enabled: yes

- name: start apache
  service:
    name: httpd
    state: started
