---
- name: check for expected content at the frontend
  uri:
    url: http://localhost
    return_content: yes
  register: webpage

- name: Fail if expected content not found on webpage
  fail:
    msg: "The smoketest failed | cleaning up instances"
  when: "'Ansible Deployed Tomcat' not in webpage.content"
